# Generated by Django 3.2.5 on 2021-08-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('genus', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('common_name', models.CharField(max_length=100)),
                ('tells', models.TextField()),
                ('other_info', models.TextField()),
                ('science_notes', models.TextField()),
                ('edibility', models.TextField()),
                ('chemical_tests', models.TextField()),
                ('links', models.TextField()),
            ],
        ),
    ]
