# Generated by Django 3.2.5 on 2021-08-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Bolete',
        ),
    ]
