# Generated by Django 3.2.5 on 2021-08-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletes', '0004_bolete_name_in_naboletes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolete',
            name='name_in_naboletes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
